import { createRoot } from 'react-dom/client';
import App from './App';
import { ErrorBoundary } from './ErrorBoundary';
import './styles.css';
import './styles/00-tokens.css';
import './styles/10-base.css';
import './styles/20-components.css';
import './styles/30-battle.css';
import './styles/40-mobile.css';
import './styles/50-refine.css';
import './styles/60-battle-intro.css';
import './styles/70-fighter-previews.css';
import './styles/71-battle-status.css';
import './styles/72-mobile-controls.css';
import './styles/73-compact-shape-shell.css';
import './styles/74-compact-shape-battle.css';
import './styles/75-compact-shape-training.css';
import './styles/76-zoom-scroll-polish.css';
import './styles/77-video-export.css';

createRoot(document.getElementById('root')!).render(<ErrorBoundary><App /></ErrorBoundary>);
